format_version: 3
pipelines:
  build_and_publish_image:
    group: sample
    label_template: 1
    lock_behavior: unlockWhenFinished
    display_order: 1
    environment_variables:
    materials:
      git:
        git: https://github.com/gocd-demo/node-bulletin-board.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - build_and_publish_image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          build_image:
            timeout: 0
            elastic_profile_id: demo-app
            artifacts:
            - external:
                id: bulletin-board
                store_id: dockerhub
                configuration:
                  options:
                    Image: vamsysivaarcca/bulletin-board
                    Tag: sample
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -t vamsysivaarcca/bulletin-board:sample . -f Dockerfile.application
                command: /bin/bash
                run_if: passed